services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nextcrm
      POSTGRES_PASSWORD: nextcrm
      POSTGRES_DB: nextcrm
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
